version: 2.1
# https://github.com/CircleCI-Public/circleci-demo-workflows/blob/workspace-forwarding/.circleci/config.yml
# persist_to_workspace issues?
# https://discuss.circleci.com/t/requesterror-x509-certificate-signed-by-unknown-authority-while-uploading-workspace/27908/2
# https://support.circleci.com/hc/en-us/articles/360016505753-Resolve-Certificate-Signed-By-Unknown-Authority-error-in-Alpine-images?flash_digest=39b76521a337cecacac0cc10cb28f3747bb5fc6a
executors:
  default-executor:
    docker:
      # Do not lead with alpine images if using 'persist_to_workspace'
      - image: circleci/openjdk:8-jdk-stretch
      - image: circleci/postgres:9.6.3-alpine
      - image: nimmis/jq 
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    working_directory: ~/circleci-demo-java-spring

orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  checkout-job:
    executor: default-executor
    parameters:
      is-merge: # do a prospective merge with master test
        type: boolean
        default: false
    steps:
      - checkout
      - when:
          condition: << parameters.is-merge >> 
          steps:
            - run:
                name: Get PR target branch.
                command: |
                  echo $"export CIRCLECI_TARGET_BRANCH=\"$(curl -s https://api.github.com/repos/deeteecee/circleci-demo-java-spring/pulls/1 | jq --raw-output '.base.ref')\"" >> $BASH_ENV
                  echo "Github target branch: $CIRCLECI_TARGET_BRANCH"
            # Test the PR merge manually. 
            - run: git fetch origin
            - run: git merge $CIRCLECI_TARGET_BRANCH
            - run: git checkout master
            - run: git merge --no-ff branch
      - attach_workspace:
          at: ~/circleci-demo-java-spring
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  build:
    executor: default-executor
    steps:
      - attach_workspace:
          at: ~/circleci-demo-java-spring
      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - codecov/upload:
          conf: codecov.yml 
          file: src/target/jacoco-reports
workflows:
  version: 2
  test:
    jobs:
      - checkout-job
      - build:
          requires:
            - checkout-job
  merge-test:
    jobs:
      - checkout-job:
          is-merge: true
      - build:
          requires:
            - checkout-job
