version: 2.1

executors:
  testecutor:
    docker:
      - image: nimmis/jq
      - image: circleci/openjdk:8-jdk-stretch
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    working_directory: ~/circleci-demo-java-spring

orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  checkout:
    executor: testecutor
    steps:
      - checkout
      - persist_to_workspace:
          root: /root
          paths:
            - circleci-demo-java-spring
  pr_checkout:
    executor: testecutor
    steps:
      - run:
          name: Get PR target branch.
          command: |
            CIRCLECI_TARGET_BRANCH=$(curl -s https://api.github.com/repos/deeteecee/circleci-demo-java-spring/pulls/1 | jq --raw-output '.base.ref')
            echo "Github target branch: $CIRCLECI_TARGET_BRANCH"
      - checkout
      - run: git merge $CIRCLECI_TARGET_BRANCH
      - persist_to_workspace:
          root: /root
          paths:
            - circleci-demo-java-spring
  build:
    executor: testecutor
    steps:
      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - codecov/upload:
          conf: codecov.yml 
          file: src/target/jacoco-reports
workflows:
  version: 2
  branch_build:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
